### PR TITLE
Add feature to import external resources like PDF

### PR DESCRIPTION
**Pull request by vishalkakadiya**
This PR will add a feature to import resources from `<a>`  tag's `href` attribute, meaning if post content is having pdf doc in anchor tag something as below:

```<a href="https://www.eagleman.com/media/Italy_Magazine_Eagleman.pdf">Something</a>```

So from the above HTML, it will take out pdf's URL, download it, upload it on the WordPress site and replace a new link in post content.

This PR is basically helpful while migrating sites from other CMS which is allowing any doc to import on site.

### CODE REVIEW

**Comment by ChrisHardie** [comment]
Hi @vishalkakadiya - great that we're updating to include PDFs. A few requests:

* Can you ignore any `.idea/` files in your commits/PRs?
* Can you set it up to define an explicit whitelist of file extensions/types that this will capture? From what I can tell, in addition to PDF files this would also capture any kind of file linked from the content, including some that we might not want.

**Comment by vishalkakadiya** [comment]
@ChrisHardie 
> Can you ignore any .idea/ files in your commits/PRs?

Sorry, that was mistakenly committed, will take care of this.

> Can you set it up to define an explicit whitelist of file extensions/types that this will capture? From what I can tell, in addition to PDF files, this would also capture any kind of file linked from the content, including some that we might not want.

Sure, I will add a condition on top of this to check file mime type, if WP is allowing that type then it will import else not, also dev can manage that via WP's mime-type filter if he needed any extra mime type to allow. Thanks!

**Comment by vishalkakadiya** [comment]
@ChrisHardie I have added a [check](https://github.com/a8cteam51/wordpress-importer-fixers/pull/21/commits/8618663503435356ebdb53a9bb77dc3b40fd543f#diff-fa69da3a58316f0fcc673e3a70afd1fcR760-R764) to import only valid/allowed mime-type files.

Let me know if anything, thanks!

**Comment by ChrisHardie** [comment]
We've been able to test this out on a few actual migrations and things seem to be working well. Merging.

**Pull request merged**
